#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)"  ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
for x in mount umount sv pacman updatedb su ; do
    alias $x="sudo $x"
done

alias \
    l="ls -lahN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    g="git" \
    e="$EDITOR" \
    v="$EDITOR" \
    p="sudo pacman" \
    tl="python ~/tradelog/cli/cli.py --prod" \
    start='cmd.exe /C start "" "$(fzf)"' \
    od='cd ~/documents/od && cmd.exe /C start "" "$(fzf)"' \
    gd='cd ~/documents/gd && cmd.exe /C start "" "$(fzf)"' \
    st='cd ~/documents && cmd.exe /C start "" "$(rg --files --hidden --follow Google\ Drive OneDrive\ -\ BZ\ inc BZ\ inc | fzf)"' \
    s1='cd ~/documents && echo "$(rg --files --hidden --follow Google\ Drive OneDrive\ -\ BZ\ inc BZ\ inc | fzf)"' \
    ss='cmd.exe /C start "" "$(rg --files --hidden --follow ./ | fzf)"' \

alias \
    gtd="git diff" \
    gts="git status" \

alias \
    va="nvim ~/.files/shell/aliasrc" \
    vl="nvim ~/.files/lf/lfrc"

alias \
    cdh='cd /mnt/c/Users/fzicat/' \
    cod='cd ~/od' \
    cgd='cd ~/gd' \

