#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)"  ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
for x in mount umount sv pacman updatedb su ; do
    alias $x="sudo $x"
done

alias \
    l="ls -lahN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    g="git" \
    e="$EDITOR" \
    v="$EDITOR" \
    p="sudo pacman" \
    tl="python ~/tradelog/cli/cli.py --prod" \
    st='cmd.exe /C start "" "$(fzf)"' \
    od='cd ~/od && cmd.exe /C start "" "$(fzf)"' \
    gd='cd ~/gd && cmd.exe /C start "" "$(fzf)"' \

alias \
    gtd="git diff" \
    gts="git status" \

alias \
    cdh='cd /mnt/c/Users/fzicat/' \
    cod='cd ~/od' \
    cgd='cd ~/gd' \

